site_name: IEEE Telepresence Initiative
site_url: https://vicarios.github.io/documentation/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Software Plugins: Software-plugins.md
  - Publications: publications.md
  - Contact: Contact.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences # Recommended for code blocks